run:
  concurrency: 8
  timeout: 5m
  tests: false
  modules-download-mode: readonly
output:
  format: colored-tab:stdout
  sort-results: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - dupword
    - errname
    - exhaustruct
    - exportloopref
    - gci
    - gochecknoinits
    - goconst
    - gocognit
    - gocyclo
    - godot
    - gofumpt
    - gomnd
    - gosec
    - ireturn
    - makezero
    - mirror
    - nilerr
    - paralleltest
    - revive
    - sqlclosecheck
    - unparam
    - wsl
    - zerologlint
    - wrapcheck
issues:
  fix: true
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
severity:
  default-severity: error
