// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/romankravchuk/effective-mobile-test-task/internal/models"
)

// PersonGetter is an autogenerated mock type for the PersonGetter type
type PersonGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *PersonGetter) Get(ctx context.Context, id string) (models.Person, error) {
	ret := _m.Called(ctx, id)

	var r0 models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Person, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Person); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Person)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPersonGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewPersonGetter creates a new instance of PersonGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPersonGetter(t mockConstructorTestingTNewPersonGetter) *PersonGetter {
	mock := &PersonGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
