name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          # NOTE: Keep this in sync with the version from go.mod
          go-version: "1.21.x"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
